name: build

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        global-json-file: ./global.json

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Install
      run: npm install

    - name: Build and test
      run: npm test
        